export const individualDays = 
[
    "Lunes",
    "Martes",
    "Miércoles",
    "Jueves",
    "Viernes",
    "Sábado",
    "Domingo"
];

export const multipleDays = 
[
    "Todos los días",
    "Toda la semana",
    "Lunes a martes",
    "Lunes a miércoles",
    "Lunes a jueves",
    "Lunes a viernes",
    "Lunes a sábado",
    "Lunes a domingo",
    "Martes a miércoles",
    "Martes a jueves",
    "Martes a viernes",
    "Martes a sábado",
    "Martes a domingo",
    "Miércoles a jueves",
    "Miércoles a viernes",
    "Miércoles a sábado",
    "Miércoles a domingo",
    "Jueves a viernes",
    "Jueves a sábado",
    "Jueves a domingo",
    "Viernes a sábado",
    "Viernes a domingo",
    "Sábado a domingo",
    "Lunes y martes",
    "Lunes y miércoles",
    "Lunes y jueves",
    "Lunes y viernes",
    "Lunes y sábado",
    "Lunes y domingo",
    "Martes y miércoles",
    "Martes y jueves",
    "Martes y viernes",
    "Martes y sábado",
    "Martes y domingo",
    "Miércoles y jueves",
    "Miércoles y viernes",
    "Miércoles y sábado",
    "Miércoles y domingo",
    "Jueves y viernes",
    "Jueves y sábado",
    "Jueves y domingo",
    "Viernes y sábado",
    "Viernes y domingo",
    "Sábado y domingo",  
];